name: parsenet
channels:
  - loopbio
  - defaults
  - pytorch
dependencies:
  - lapsolver=1.0.2=py36h4af77d5_0
  - python=3.6.6=h6e4f718_2
  - pip:
    - geomdl==5.2.9
    - h5py==2.10.0
    - lap==0.4.0
    - open3d==0.9.0.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - six==1.13.0
    - sklearn==0.0
    - tensorboard-logger==0.1.0
    - torch==1.2.0
    - torchvision==0.4.0
    - transforms3d==0.3.1
    - trimesh==2.31.38
    - pip==20.0.2