name: pytorch_1.2
channels:
  - loopbio
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py36_0
  - lapsolver=1.0.2=py36h4af77d5_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.0.2u=h7b6447c_0
  - python=3.6.6=h6e4f718_2
  - readline=7.0=h7b6447c_5
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.3
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - configobj==5.0.6
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - distlib==0.3.0
    - entrypoints==0.3
    - filelock==3.0.12
    - fuckit==4.8.1
    - geomdl==5.2.9
    - h5py==2.10.0
    - imageio==2.6.1
    - importlib-metadata==1.3.0
    - importlib-resources==1.4.0
    - ipdb==0.12.3
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jinja2==2.10.3
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - lap==0.4.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - networkx==2.4
    - notebook==6.0.2
    - numpy==1.18.0
    - open3d==0.9.0.0
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==7.0.0
    - pip==20.0.2
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.2
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - pyflakes==2.1.1
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.6
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - pyyaml==5.3
    - pyzmq==18.1.1
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - setuptools==44.0.0
    - six==1.13.0
    - sklearn==0.0
    - tensorboard-logger==0.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.2.0+cu92
    - torchvision==0.4.0+cu92
    - tornado==6.0.3
    - traitlets==4.3.3
    - transforms3d==0.3.1
    - trimesh==2.31.38
    - typing==3.7.4.1
    - virtualenv==20.0.18
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==0.6.0
prefix: /home/gopalsharma/softwares/anaconda/envs/pytorch_1.2